import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "../components/ui/accordion";

interface QuestionProp {
  question: string;
  answer: string;
  value: string;
}

const QuestionsList: QuestionProp[] = [
  {
    question: "How does the email summarization feature work ?",
    answer: "The email summarization feature utilizes advanced transformer models to analyze and condense long emails " +
        "into concise summaries. It extracts key sentences or phrases that capture the main points of the email, " +
        "enabling users to quickly grasp essential information without reading through the entire message.",
    value: "item-1",
  },
  {
    question: "What benefits does email categorization provide ?",
    answer:
      "Email categorization automatically sorts incoming emails into predefined folders such as work, personal, and promotions based on content analysis and user-defined rules. " +
        "This organizational feature helps users prioritize their inbox, reduce clutter, and efficiently manage their correspondence.",
    value: "item-2",
  },
  {
    question:
      "How are suggested responses generated by the email assistant ?",
    answer:
      "The email assistant generates suggested responses using natural language processing (NLP) models. It analyzes the " +
        "content and context of incoming emails to propose relevant replies for common types of messages. This feature saves " +
        "time by offering quick-reply options that users can customize or send with minimal editing.",
    value: "item-3",
  },
  {
    question: "What technologies are used for implementing email search and filtering ?",
    answer: "Email search and filtering are implemented using advanced search algorithms and filtering techniques integrated " +
        "with the email client. Technologies such as Elasticsearch may be employed for fast and efficient retrieval " +
        "of specific emails based on criteria like sender, subject, keywords, and date ranges.\n",
    value: "item-4",
  },
  {
    question:
      "How does the email assistant contribute to productivity and efficiency ?",
    answer:
      "The email assistant enhances productivity by streamlining email management tasks. It reduces the time spent on reading " +
        "lengthy emails with summarization, organizes messages for easier access with categorization, provides quick-reply options " +
        "with suggested responses, and facilitates quick retrieval of relevant emails through robust search and filtering capabilities. " +
        "These features collectively help users stay organized, respond promptly,and focus on high-priority tasks.",
    value: "item-5",
  },
];

export const FAQ = () => {
  return (
    <section
      id="faq"
      className="container py-24 sm:py-32"
    >
      <h2 className="text-3xl md:text-4xl font-bold mb-4">
        Question you might{" "}
        <span className="bg-gradient-to-b from-primary/60 to-primary text-transparent bg-clip-text">
          have
        </span>
      </h2>

      <Accordion
        type="single"
        collapsible
        className="w-full AccordionRoot"
      >
        {QuestionsList.map(({ question, answer, value }: QuestionProp) => (
          <AccordionItem
            key={value}
            value={value}
          >
            <AccordionTrigger className="text-left">
              {question}
            </AccordionTrigger>

            <AccordionContent>{answer}</AccordionContent>
          </AccordionItem>
        ))}
      </Accordion>

      <h3 className="font-medium mt-4">
        Still have questions?{" "}
        <a
          rel="noreferrer noopener"
          href="#"
          className="text-primary transition-all border-primary hover:border-b-2"
        >
          Contact us
        </a>
      </h3>
    </section>
  );
};
